Add Auth0 support
PartidoDigital/DemocracyOS-App pull request #3
Opened 2017-10-25 14:37 UTC by lomegor

2017-10-25 14:44 UTC, leog commented
Tremendo laburo @lomegor, muchas gracias.

Se me ocurre que solo vamos a habilitar el ingreso mediante Auth0 y me parece que estaría bueno modificar los textos para que diga solamente "Ingresar" porque si bien usamos Auth0, debería ser transparente al usuario final qué medio utilizamos. Así que si podes modificar los textos para que diga solamente "Ingresar", sería un golazo. 

Cuando mergiemos este PR vamos a ver si podemos deployar en la instancia de prueba en Heroku para probarlo y ver como queda todo. Can't wait!

2017-10-25 15:11 UTC, lomegor commented
done

2017-10-25 17:46 UTC, leog requested changes

2017-10-25 17:46 UTC, leog commented on lib/translations/lib/es.json
> +  "signin.error.using-auth0": "La dirección de correo electrónico ya fue usada ingresando con Auth0",
Acá me refería a sacar Auth0

2017-10-25 17:46 UTC, leog commented on lib/translations/lib/es.json
> +  "signin.login-with-auth0": "Ingresar con Auth0",
Acá también

2017-10-26 08:46 UTC, lomegor commented
Ah, ahora te entendi. Lo que habia hecho antes fue sacar el basic form (porque no es una opcion) cuando auth0 esta habilitado. El error que dice que el e-mail ya esta siendo usado nunca se deberia dar porque eso es solo si intentas usar el basic auth, pero el usuario esta registrado con auth0

2017-11-09 23:27 UTC, lomegor commented
@leog Decime que te parece ahora y si lo podemos poner en Heroku. Todavia peleando con las extensiones

2017-11-09 23:58 UTC, leog approved these changes

2017-11-09 23:58 UTC, merged